<?php 
ob_start();
session_start();
include("config/config.php");
include("includes/functions.php");
//include("includes/constants.php");
include("classes/Database.class.php");
include("classes/validator.class.php");
?>